

CREATE TABLE IF NOT EXISTS words
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    word VARCHAR(50),
    russian VARCHAR(50),
    addition_date TIMESTAMP WITHOUT TIME ZONE
    );

CREATE TABLE IF NOT EXISTS nouns
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    word VARCHAR(50)                        ,
    russian VARCHAR(50)                        ,
    addition_date TIMESTAMP  WITHOUT TIME ZONE,
    plural VARCHAR(50)                        ,
    article VARCHAR(50)                        ,
    CONSTRAINT pk_categories PRIMARY KEY (id)
    );
