--DROP table if exists nouns, verbs, users;

CREATE TABLE IF NOT EXISTS nouns
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    word VARCHAR(50)                        ,
    russian VARCHAR(50)                        ,
    addition_date TIMESTAMP  WITHOUT TIME ZONE,
    plural VARCHAR(50)                        ,
    article VARCHAR(50)                        ,
    CONSTRAINT pk_nouns PRIMARY KEY (id),
    CONSTRAINT uq_nouns UNIQUE (word)
    );

CREATE TABLE IF NOT EXISTS users
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(1000)                        ,
    password VARCHAR(1000)                        ,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS verbs
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    word VARCHAR(50)                        ,
    russian VARCHAR(50)                        ,
    addition_date TIMESTAMP  WITHOUT TIME ZONE,
    partizip_zwei VARCHAR(50)                        ,
    hilfsverb VARCHAR(50)                        ,
    CONSTRAINT pk_verbs PRIMARY KEY (id)
);

-- CREATE TABLE IF NOT EXISTS users
-- (
--     id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     name VARCHAR(50)                        ,
--     password VARCHAR(50)   ,
--     CONSTRAINT pk_users PRIMARY KEY (id)
-- );
